# Generated by Django 4.1.4 on 2022-12-27 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='question',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.question', verbose_name='Questão'),
            preserve_default=False,
        ),
    ]
